Repository AgentSingle/vet, pull requests merged in 2024-03, with the labels that each got.

#1 Update
  .gitignore
  README.md
  index.html
  public/vet.svg
  public/vite.svg
  src/App.vue
  src/assets/Vet_Screen_Short.png
  src/components/Home.vue
  src/components/VET/javascript/randomDataGenerator.js
  src/components/VET/vue/veTable.vue
  src/components/VET/vue/veTableHeading.vue
  src/components/VET/vue/vet.vue
Labels: enhancement

#3 VERSION-0.0.6, modify
  src/components/Home.vue
  src/components/VET/javascript/randomDataGenerator.js
  src/components/VET/vue/veTableHeading.vue
  src/components/VET/vue/vet.vue
  src/components/VET/vue/vetInput.vue
Labels: enhancement, BugFix

#5 Update
  .github/diploy.yml
  .github/testFont.yml
  src/assets/Vet_Screen_Short.png
Labels: enhancement

#8 Update
  .github/workflows/diploy.yml
Labels: enhancement

#35 Version-0.4.6, readme file change
  src/components/VET/vue/vet.vue
Labels: enhancement, BugFix, fix

#36 Update
  src/assets/Vet_Screen_Short.png
  src/components/VET/vue/vetInput.vue
Labels: BugFix

#42 VERSION-0.6.4
  src/components/VET/icon/IconDeleteAll.vue
  src/components/VET/icon/IconSave.vue
  src/components/VET/vue/veTableHeading.vue
  src/components/VET/vue/vet.vue
Labels: enhancement, BugFix
